teleop:
  ros__parameters:
    joy_topic: /mecanumbot/joy
    twist_topic: /mecanumbot/joy
    move:
      forward:
        axis: 1
        scale: 1.0
        deadzone: 0.0
      reverse:
        axis: 1
        scale: 1.0
        deadzone: 0.0
      left:
        axis: 0
        scale: 1.0
        deadzone: 0.0
      right:
        axis: 0
        scale: 1.0
        deadzone: 0.0
    turn:
      left:
        axis: 5
        scale: 1.0
        deadzone: 0.0
      right:
        axis: 4
        scale: -1.0
        deadzone: 0.0

joystick:
  ros__parameters:
    joy_topic: /mecanumbot/joy
    dev: /dev/input/js0
    deadzone: 0.2